### PR TITLE
Add option to disable encryption

### PR DESCRIPTION
**Pull request by arj03**
The idea with this change is that we can reuse all the existing logic and just disable encryption on a local network. The reason to still do authentication on a local machine is to ensure that you have access to the private key. The overhead of encrypting is quite substantial. On my machine streaming 100k json messages from a flume logs is roughly double the speed. See this thread for [discussion](https://github.com/ssbc/secret-stack/pull/21) of how this can be used in scuttlebot.

### CODE REVIEW

**Comment by cryptix** [comment]
Having a crypto library with an off switch feels a bit weird.

Can’t we have secret-stack just pass through instead of passing this down into she/boxstream?

**Comment by dominictarr** [comment]
Also, this means that although it isn't used to provide any privacy, the private key still needs to be accessed by every program that can connect. Is there an advantage to this over just allowing access to things we know have local access? (i.e. via socket, or checking the domain if it's a websocket from a local website, for example)

**Comment by arj03** [comment]
I already have a noauth plugin that does what you describe @dominictarr . What I wanted with this change is a shs-handshake-only plugin which I can enable so that I know that programs talking to my sbot locally has access to the secret key file. Otherwise any program runnning on my machine could stream my whole db and send it somewhere just by connecting to a socket or localhost.

**Comment by dominictarr** [comment]
@arj03 when we started working on ssb, I remember disucssing with paul what we could do about threats from "programs running on localhost" and basically decided that there isn't much to be done to protect against programs running on localhost...

I guess you can set the private key as user owner so that processes running as "nobody" can't read it. (pretty sure you can do this to a socket too, but not a network port). However most programs run as the user anyway, so this doesn't really get us that much.

locally open web pages are definitely a threat, since it would be easy to get someone to click a link, but then the browser (which is trusted) gives a domain, so we could have a whitelist of domains.

If we keep the private key out of local host authorizations, then it means we copy the key less places... I think this is a bigger security benefit.

another idea: instead of authorizing with the private key... what if we just have a simpler handshake to auth local apis, something like: send `[timestamp, app, hmac(key, app+timestamp)]` don't allow timestamps mor than than 3 seconds in the past or future, or the last connection time for that app. That prevents replay attacks.

then have a symmetric key per app, that is created by some user action? I think that would allay @cryptix's concerns, but also have a way for apps to be positively authorized, @arj03's concerns.

**Comment by arj03** [comment]
Alright, I like the hmac solution. That way we also have a way of knowing what app is connecting.

The reason why I bring this up is that I think in the future more applications are going to be sandboxed. Systemd already has some quite good defaults in place and I want to make sure that we can support this going forward.

Thanks for both of your feedback!

**Pull request closed without merging**
