### PR TITLE
Make output state closer to minimal

### PR DESCRIPTION
**Pull request by 1082008**
Sensitive properties of the state should be deleted instead only being nullified. This helps to minimalize test vectors.

### CODE REVIEW

**Comment by arj03** [comment]
Just ran into this. Looks good to me.

**Comment by christianbundy** [comment]
Is this safer / faster than `Buffer.prototype.fill(0)`?

**Comment by cryptix** [comment]
Without known the internals of V8s garbage collector, I'd argue that it's safer to overwrite the data with zeros and then instructing the GC to free it, since you can't influence _when_ it does they.

**Comment by christianbundy** [comment]
Agreed, it's also what our libsodium providers do,

**Comment by dominictarr** [comment]
I had to check, this function already fills with zeros, but that's not show in this diff because it's on other lines. delete vs set to null makes no difference from security perspective. indeed, there is no knowing when the GC will actually "collect" the memory, but when it does it does not zero it, and will not overwrite it until that memory is reallocated.

I don't see why minimal test vectors really matters that much but up to you guys... possibly it may be easier to parse in a typed language if the format stays the same shape.

**Comment by staltz** [comment]
Can we close this PR? @1082008 @LaszloAshin It's not clear how exactly this helps "minimalize" test vectors.

**Comment by 1082008** [comment]
I'm fine with closing this.

**Pull request closed without merging**
